### ISSUE TITLE
Change logger to test_case_logging

### ISSUE THREAD

**Issue by kgrozis-arista** [aristanetworks/vane#178]
**Is your feature request related to a problem? Please describe.**
logger.py is a non-descriptive file for what it does.  It needs to be changed to a file name that let's developer know what it does.

**Describe the solution you'd like**
* Change name to test_case_logging.py
* Keep the logger.py for backwards compatibility
* Create issue to refactor test cases and use new test_case_logging.py

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by rewati-arista** [comment]
The PR for https://github.com/aristanetworks/vane/issues/346: https://github.com/aristanetworks/vane/pull/368 address this, now only logger.py needs to be retracted which will happen when https://github.com/aristanetworks/vane/issues/179 gets addressed so closing this issue
