### ISSUE TITLE
[Defect] Testcase description(TD) is not added in .md file

### ISSUE THREAD

**Issue by vishwajeetgslab** [aristanetworks/vane#21]
### Summary
As observed for latest Vane version, Testcase description(TD) added in testcase file is not added in the .md file created after the test execution.

### Expected Behavior
Testcase description should be added in .md file for each of the testcase after test execution. Please find screenshot for reference.(Screenshot added here is taken from older vane version)

<img width="533" alt="image" src="https://user-images.githubusercontent.com/61869155/217037204-ad25e70d-d7db-49fc-8683-b9b848060e3e.png">

### Actual Behavior
Testcase description is not added in the .md file after the execution of testcase. (Found this issue with latest vane)
<img width="497" alt="image" src="https://user-images.githubusercontent.com/61869155/217037380-2c9d2774-c852-46c1-a639-24eb02bcfb69.png">

**Comment by rewati-arista** [comment]
Duplicate issue https://github.com/aristanetworks/vane/issues/210 solved here https://github.com/aristanetworks/vane/pull/219
