### ISSUE TITLE
Write skipped test cases to docx report

### ISSUE THREAD

**Issue by kgrozis-arista** [aristanetworks/vane#273]
**Is your feature request related to a problem? Please describe.**
Currently, a skipped test case is not added to the docx report. Users want reporting on skipped test case and to know why it has been skipped.

**Describe the solution you'd like**
Change reporting to report the reason for a skipped test case:
* If it is defined in the test case using the skipped decorator report this
* If a DUT in the parameterized decorator does not match duts.yml file report this

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by rewati-arista** [comment]
Duplicate at https://github.com/aristanetworks/vane/issues/486
