### ISSUE TITLE
Packet Generator Design

### ISSUE THREAD

**Issue by kgrozis-arista** [aristanetworks/vane#316]
**Is your feature request related to a problem? Please describe.**
Need to integrate Packet generators into Vane

**Describe the solution you'd like**
Use requirements to create a design: https://docs.google.com/document/d/1ydug7Ha9DxcdEz2413NAxRbrs9DpNigwusO99rWbSjA/edit
Create common packet generator object.  Object will have drivers for vendor specific features.

**Describe alternatives you've considered**
Research other popular packet generators besides Ixia 

**Additional context**

**Comment by rewati-arista** [comment]
Module design:

![Image](https://github.com/aristanetworks/vane/assets/123415500/b799721f-42e9-433b-ac21-9b896128a3f4)
