### ISSUE TITLE
Create Master Definitions file for NRFU test case setup

### ISSUE THREAD

**Issue by kgrozis-arista** [aristanetworks/vane#359]
**Is your feature request related to a problem? Please describe.**
In NRFU test case, have a single file to change test case parameters

**Describe the solution you'd like**
In most cases, NRFU test cases will be written without needing additional parameters and the operator can run the suite without additional input.  For those NRFU test cases that have modifiable parameters, a single setup file will be available to input or change these parameters.  Use master definition file to accomplish this.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by rewati-arista** [comment]
Closing as more relevant to Test case development
