### ISSUE TITLE
Convert Pytest-CVP DNS test case to Vane

### ISSUE THREAD

**Issue by kgrozis-arista** [aristanetworks/vane#419]
**Is your feature request related to a problem? Please describe.**
Convert PyTest-CVP DNS test case:  https://gitlab-gslab.act.arista.com/kgrozis/pytest-cvp/-/blob/main/test_cases/base_services_dns_test.py

**Describe the solution you'd like**
PyTest-CVP DNS test case should have the following:
* Use Vane test case styling
* Use Master definition file to simplify input
* Add test case steps to the test case
* Test case should be skipped if DNS is not configured
* Test should be added to top-level directory nrfu_tests
* Use markers nrfu_test, base_services
* Use test case id: NRFU1.1

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by AbhijeetGSLAB** [comment]
Closing the issue as MR is merged
