### ISSUE TITLE
Convert Pytest-CVP SSO test case to Vane

### ISSUE THREAD

**Issue by kgrozis-arista** [aristanetworks/vane#421]
**Is your feature request related to a problem? Please describe.**
Convert PyTest-CVP SSO test case:  https://gitlab-gslab.act.arista.com/kgrozis/pytest-cvp/-/blob/main/test_cases/base_services_redundancy_sso_test.py

**Describe the solution you'd like**
PyTest-CVP SSO test case should have the following:
* Use Vane test case styling
* Use Master definition file to simplify input
* Add test case steps to the test case
* Test case should be skipped if SSO is not configured
* Test should be added to top-level directory nrfu_tests
* Use markers nrfu_test, base_services
* Use Test ID: NRFU1.3

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by AbhijeetGSLAB** [comment]
Closing the issue as the MR is merged
