### ISSUE TITLE
Convert Pytest-CVP TACACS test case to Vane

### ISSUE THREAD

**Issue by kgrozis-arista** [aristanetworks/vane#422]
**Is your feature request related to a problem? Please describe.**
Convert PyTest-CVP TACACS test case:  https://gitlab-gslab.act.arista.com/kgrozis/pytest-cvp/-/blob/main/test_cases/base_services_tacacs_test.py

**Describe the solution you'd like**
PyTest-CVP TACACS test case should have the following:
* Use Vane test case styling
* Use Master definition file to simplify input
* Add test case steps to the test case
* Test case should be skipped if TACACS is not configured
* Test should be added to top-level directory nrfu_tests
* Use markers nrfu_test, base_services
* Use Test ID: NRFU1.4
**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by hsisalgslab** [comment]
Closing this task as MR is merged
