### ISSUE TITLE
Convert Pytest-CVP interface errors and discards test case to Vane

### ISSUE THREAD

**Issue by kgrozis-arista** [aristanetworks/vane#425]
**Is your feature request related to a problem? Please describe.**
Convert PyTest-CVP interface errors and discards test case:  https://gitlab-gslab.act.arista.com/kgrozis/pytest-cvp/-/blob/main/test_cases/interfaces_errors_and_discards_test.py

**Describe the solution you'd like**
PyTest-CVP interface errors and discards test case should have the following:
* Use Vane test case styling
* Use Master definition file to simplify input
* Add test case steps to the test case
* Test should be added to top-level directory nrfu_tests
* Use markers nrfu_test, interfaces
* Use Test ID: NRFU2.3

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by rahulmali2512** [comment]
PR closed as it is Merged
