### ISSUE TITLE
Convert Pytest-CVP MLAG status check test case to Vane

### ISSUE THREAD

**Issue by kgrozis-arista** [aristanetworks/vane#426]
**Is your feature request related to a problem? Please describe.**
Convert PyTest-CVP MLAG status check test case:  https://gitlab-gslab.act.arista.com/kgrozis/pytest-cvp/-/blob/main/test_cases/interfaces_mlag_status_check_test.py

**Describe the solution you'd like**
PyTest-CVP MLAG status check test case should have the following:
* Use Vane test case styling
* Use Master definition file to simplify input
* Add test case steps to the test case
* Test case should be skipped if MLAG is not configured
* Test should be added to top-level directory nrfu_tests
* Use markers nrfu_test, interfaces
* Use Test ID: NRFU2.4

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by paragpande24** [comment]
PR closed as it is merged.
