### ISSUE TITLE
Convert Pytest-CVP Port-Channel test case to Vane

### ISSUE THREAD

**Issue by kgrozis-arista** [aristanetworks/vane#428]
**Is your feature request related to a problem? Please describe.**
Convert PyTest-CVP Port-Channel  test case:  https://gitlab-gslab.act.arista.com/kgrozis/pytest-cvp/-/blob/main/test_cases/interfaces_port_channels_test.py

**Describe the solution you'd like**
PyTest-CVP Port-Channel test case should have the following:
* Use Vane test case styling
* Use Master definition file to simplify input
* Add test case steps to the test case
* Test case should be skipped if Port-Channel is not configured
* Test should be added to top-level directory nrfu_tests
* Use markers nrfu_test, interfaces
* Use Test ID: NRFU2.6

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by geetanjalimanegslab** [comment]
MR for this task is merged hence closing this task
