### ISSUE TITLE
Convert Pytest-CVP misc show test case to Vane

### ISSUE THREAD

**Issue by kgrozis-arista** [aristanetworks/vane#429]
**Is your feature request related to a problem? Please describe.**
Convert PyTest-CVP misc show test case: https://gitlab-gslab.act.arista.com/kgrozis/pytest-cvp/-/blob/main/test_cases/misc_show_commands_test.py

**Describe the solution you'd like**
PyTest-CVP misc show test case should have the following:
* Use Vane test case styling
* Use Master definition file to simplify input
* Add test case steps to the test case
* Test should be added to top-level directory nrfu_tests
* Use markers nrfu_test, misc
* Use Test ID: NRFU3.1

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by hsisalgslab** [comment]
- closing this task as MR is merged
