### ISSUE TITLE
Convert Pytest-CVP Routing Multi-Agent test case to Vane

### ISSUE THREAD

**Issue by kgrozis-arista** [aristanetworks/vane#433]
**Is your feature request related to a problem? Please describe.**
Convert PyTest-CVP Routing Multi-Agent test case:  https://gitlab-gslab.act.arista.com/kgrozis/pytest-cvp/-/blob/main/test_cases/routing_multi_agent_test.py

**Describe the solution you'd like**
PyTest-CVP Routing Multi-Agent test case should have the following:
* Use Vane test case styling
* Use Master definition file to simplify input
* Add test case steps to the test case
* Test should be added to top-level directory nrfu_tests
* Use markers nrfu_test, routing
* Use Test ID: NRFU4.4

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by vitthalmagadum** [comment]
Closing the task as respective MR is merged.
