### ISSUE TITLE
Convert Pytest-CVP API access test case to Vane

### ISSUE THREAD

**Issue by kgrozis-arista** [aristanetworks/vane#434]
**Is your feature request related to a problem? Please describe.**
Convert PyTest-CVP API access test case:  https://gitlab-gslab.act.arista.com/kgrozis/pytest-cvp/-/blob/main/test_cases/security_rp_api_access_list_test.py

**Describe the solution you'd like**
PyTest-CVP API access test case should have the following:
* Use Vane test case styling
* Use Master definition file to simplify input
* Add test case steps to the test case
* Test should be added to top-level directory nrfu_tests
* Use markers nrfu_test, security
* Use Test ID: NRFU5.1

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by rohitsinghgslab** [comment]
Closing issue, as PR is merged.
