### ISSUE TITLE
Convert Pytest-CVP L2 VLAN Name test case to Vane

### ISSUE THREAD

**Issue by kgrozis-arista** [aristanetworks/vane#435]
**Is your feature request related to a problem? Please describe.**
Convert PyTest-CVP L2 VLAN Name test case:  https://gitlab-gslab.act.arista.com/kgrozis/pytest-cvp/-/blob/main/test_cases/security_rp_l2_vlan_name_test.py

**Describe the solution you'd like**
PyTest-CVP L2 VLAN Name test case should have the following:
* Use Vane test case styling
* Use Master definition file to simplify input
* Add test case steps to the test case
* Test case should be skipped if VLANs is not configured
* Test should be added to directory sample_network_tests/nrfu
* Use markers nrfu_test, security
* Use Test ID: NRFU5.4

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by rahulrajolegslab** [comment]
closing task as MR is merged.
