### ISSUE TITLE
Convert Pytest-CVP Bad SysLog test case to Vane

### ISSUE THREAD

**Issue by kgrozis-arista** [aristanetworks/vane#440]
**Is your feature request related to a problem? Please describe.**
Convert PyTest-CVP Bad SysLog test case:  https://gitlab-gslab.act.arista.com/kgrozis/pytest-cvp/-/blob/main/test_cases/system_hardware_bad_syslog_test.py

**Describe the solution you'd like**
PyTest-CVP Bad SysLog test case should have the following:
* Use Vane test case styling
* Use Master definition file to simplify input
* Add test case steps to the test case
* Test case should be skipped if SysLog is not configured
* Test should be added to top-level directory nrfu_tests
* Use markers nrfu_test, system
* Use Test ID: NRFU6.1

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by rahulmali2512** [comment]
PR closed as it is Merged
