### ISSUE TITLE
Convert Pytest-CVP CPU Idle test case to Vane

### ISSUE THREAD

**Issue by kgrozis-arista** [aristanetworks/vane#443]
**Is your feature request related to a problem? Please describe.**
Convert PyTest-CVP CPU Idle test case:  https://gitlab-gslab.act.arista.com/kgrozis/pytest-cvp/-/blob/main/test_cases/system_hardware_cpu_idle_test.py

**Describe the solution you'd like**
PyTest-CVP CPU Idle test case should have the following:
* Use Vane test case styling
* Use Master definition file to simplify input
* Add test case steps to the test case
* Test case should be skipped if CPU Idle is not configured
* Test should be added to directory sample_network_tests/nrfu
* Use markers nrfu_test, system
* Use Test ID: NRFU6.4

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by Dakshatagslab** [comment]
Closing this task as MR is merged
