### ISSUE TITLE
Convert Pytest-CVP Fan Status test case to Vane 

### ISSUE THREAD

**Issue by kgrozis-arista** [aristanetworks/vane#444]
**Is your feature request related to a problem? Please describe.**
Convert PyTest-CVP Fan Status  test case:  https://gitlab-gslab.act.arista.com/kgrozis/pytest-cvp/-/blob/main/test_cases/system_hardware_fan_status_test.py

**Describe the solution you'd like**
PyTest-CVP Fan Status  test case should have the following:
* Use Vane test case styling
* Use Master definition file to simplify input
* Add test case steps to the test case
* Test case should be skipped if vEOS
* Test should be added to top-level directory nrfu_tests
* Use markers nrfu_test, system
* Use Test ID: NRFU6.5

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by rohitsinghgslab** [comment]
Closing, as PR is merged
