### ISSUE TITLE
Convert Pytest-CVP Flash Free test case to Vane

### ISSUE THREAD

**Issue by kgrozis-arista** [aristanetworks/vane#445]
**Is your feature request related to a problem? Please describe.**
Convert PyTest-CVP Flash Free test case:  https://gitlab.aristanetworks.com/clay/pytest-test-cases/-/blob/main/test_cases/system_hardware_flash_free_space_test.py

**Describe the solution you'd like**
PyTest-CVP Flash Free test case should have the following:
* Use Vane test case styling
* Use Master definition file to simplify input
* Add test case steps to the test case
* Test should be added to top-level directory nrfu_tests
* Use markers nrfu_test, system
* Use Test ID: NRFU6.6

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by MaheshGSLAB** [comment]
MR got merged hence closing this task
