### ISSUE TITLE
Convert Pytest-CVP Free Memory test case to Vane

### ISSUE THREAD

**Issue by kgrozis-arista** [aristanetworks/vane#446]
**Is your feature request related to a problem? Please describe.**
Convert PyTest-CVP Free Memory test case:  https://gitlab-gslab.act.arista.com/kgrozis/pytest-cvp/-/blob/main/test_cases/system_hardware_free_memory_test.py

**Describe the solution you'd like**
PyTest-CVP Free Memory test case should have the following:
* Use Vane test case styling
* Use Master definition file to simplify input
* Add test case steps to the test case
* Test should be added to top-level directory nrfu_tests
* Use markers nrfu_test, system
* Use Test ID: NRFU6.7

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by rahulrajolegslab** [comment]
closing task as MR is merged.
