### ISSUE TITLE
Convert Pytest-CVP Power Supply Status case to Vane

### ISSUE THREAD

**Issue by kgrozis-arista** [aristanetworks/vane#448]
**Is your feature request related to a problem? Please describe.**
Convert PyTest-CVP Power Supply Status test case:  https://gitlab-gslab.act.arista.com/kgrozis/pytest-cvp/-/blob/main/test_cases/system_hardware_power_supply_status_test.py

**Describe the solution you'd like**
PyTest-CVP Power Supply Status test case should have the following:
* Use Vane test case styling
* Use Master definition file to simplify input
* Add test case steps to the test case
* Test case should be skipped if vEOS
* Test should be added to directory sample_network_tests/nrfu
* Use markers nrfu_test, system
* Use Test ID: NRFU6.9

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by Ashutosh-GSLAB** [comment]
closing the PR as it is merged.
