### ISSUE TITLE
Convert Pytest-CVP Power Supply Voltage test case to Vane 

### ISSUE THREAD

**Issue by kgrozis-arista** [aristanetworks/vane#449]
**Is your feature request related to a problem? Please describe.**
Convert PyTest-CVP Power Supply Voltage test case:  https://gitlab-gslab.act.arista.com/kgrozis/pytest-cvp/-/blob/main/test_cases/system_hardware_power_supply_voltage_test.py

**Describe the solution you'd like**
PyTest-CVP Power Supply Voltage test case should have the following:
* Use Vane test case styling
* Use Master definition file to simplify input
* Add test case steps to the test case
* Test case should be skipped if vEOS
* Test should be added to top-level directory nrfu_tests
* Use markers nrfu_test, system
* Use Test ID: NRFU6.10

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by vishwajeetgslab** [comment]
closing task as MR is merged.
