### ISSUE TITLE
Convert Pytest-CVP Enable Password test case to Vane

### ISSUE THREAD

**Issue by kgrozis-arista** [aristanetworks/vane#453]
**Is your feature request related to a problem? Please describe.** 
Convert PyTest-CVP Enable Password test case: https://gitlab-gslab.act.arista.com/kgrozis/pytest-cvp/-/blob/main/test_cases/security_rp_enable_pw_test.py

**Describe the solution you'd like**
PyTest-CVP Enable Password  test case should have the following:
* Use Vane test case styling
* Use Master definition file to simplify input
* Add test case steps to the test case
* Test should be added to top-level directory nrfu_tests
* Use markers nrfu_test, security
* Use Test ID: NRFU5.2

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by Dakshatagslab** [comment]
Closing this task as MR is merged
