### ISSUE TITLE
Test suite name is not correct in Docx report

### ISSUE THREAD

**Issue by MaheshGSLAB** [aristanetworks/vane#459]
**Is your feature request related to a problem? Please describe.**
Test suite name is reflecting incorrect in Docx report. If there is an underscore in test suite name then it shows half name of test suite. In case if testsuite name in camel case then test suite name come as list under Test Case Results Summary.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Here is the snap from docx reports for both case.
1. If there is underscore in test suite name. Expected test suite name is sr_te but reflecting as Te.
![image](https://github.com/aristanetworks/vane/assets/122076792/1d870a5f-a7da-473a-8a72-99c41074cc89)

2. If test suite name in camel case. 
![image](https://github.com/aristanetworks/vane/assets/122076792/d53ca57c-fa7a-4086-b19b-495e7d6be696)

**Comment by rewati-arista** [comment]
@MaheshGSLAB for (1) that is how the naming of test suites is expected: "Test_Suite" and whatever "Suite" is gets picked up for the value. So in your case "Te" is supposed to be the suite name. Does that make sense? Lets discuss this in our next sync when Kevin is there

For (2) I will get a fix in.

**Comment by rewati-arista** [comment]
https://github.com/aristanetworks/vane/pull/528
