### ISSUE TITLE
There should be hyperlinks in the test case summary section to detailed test case section

### ISSUE THREAD

**Issue by kgrozis-arista** [aristanetworks/vane#467]
**Is your feature request related to a problem? Please describe.**
It would be easier for user to have a hyperlink in the test case summary section.  This link will directly access the detailed test case information.  This way the way user will not need to scroll or look in table of contents for more information.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rewati-arista** [comment]
Duplicate at: https://github.com/aristanetworks/vane/issues/375
