### ISSUE TITLE
Vane errors out when test cases executed with marker

### ISSUE THREAD

**Issue by vishwajeetgslab** [aristanetworks/vane#487]
**Description:**
When marker is added in definitions.yaml file to execute the test cases for a particular marker then vane gives an error and test execution stops.

**Describe the solution you'd like**
Test cases should be executed for particular marker, When marker is added in definitions.yaml file.

**Describe alternatives you've considered**
If marker field is kept empty in defintions.yaml file and test cases executed by test directory, then it works.

**Additional context**
Snapshot for reference:
<img width="742" alt="image" src="https://github.com/aristanetworks/vane/assets/61869155/e3045d66-f8e1-4e28-9a4d-9de1c695fd7d">

**Comment by rewati-arista** [comment]
So @vishwajeetgslab I tried running Vane (recent develop and recent main branch) with markers and it runs fine for me. Can you tell me how I could reproduce this, since I am not running into this issue.

**Comment by rewati-arista** [comment]
The above solution resolved the error
