### ISSUE TITLE
Fix the TypeError observed in NRFU4.3 test case.

### ISSUE THREAD

**Issue by vishwajeetgslab** [aristanetworks/vane#581]
As observed while running NRFU test case, NRFU4.3
 test case is failing with TypeError. Please investigate it and Fix it.

<img width="447" alt="image" src="https://github.com/aristanetworks/vane/assets/61869155/ac4787ad-a47d-4570-9eea-b46416c4dd0e">

**Comment by vitthalmagadum** [comment]
Closing the task as respective MR is merged.
