### ISSUE TITLE
Add an API to support evidence recording for commands executed via non-eAPI or non-netmiko connections

### ISSUE THREAD

**Issue by vishwajeetgslab** [aristanetworks/vane#651]
Few of the commands like `tcpdump monitor DVT packet-count 10 size 100 verbose filter mpls 902000 && mpls 1003000 && mpls 913069`, `tcpdump monitor DVT packet-count 100 size 1000 verbose` cannot be run using pyeapi/netmiko connections. The tests might want to run these commands using their own custom utilities. However the evidence of these commands run by custom utilities is not available to vane and hence does not get collected in the docx or HTML reports. 
The solution could be adding a API to vane that the tests can call to add the evidence to vane TestsOps class. 

With the help of this API user should be able to ingest/record the output collected from the devices using any other connection library(like paramiko, pysnmp) in the DOCx and html reports.

API to be added within tests_tools.py: TestOps module

Suggested API interface : `add_cmds_evidence(dut : str, prompt : str, cmds : list[str], cmds_output: list[str])`
Args:
`dut`: name of dut to which this evidence is to be added. 
`prompt` takes two values: <vane_server, or dut_name> and it indicates where the command was run.
`cmds`: list of cmds run 
`cmds_output`: list of ouptuts of above `cmds`

**Comment by vishwajeetgslab** [comment]
@rewati-arista @shachiagarwal

**Comment by rewati-arista** [comment]
> @rewati-arista @shachiagarwal

LGTM, added minor detail about location. Thanks!

**Comment by shachiagarwal** [comment]
I have updated the Description. Please take a look. @rewati-arista @vishwajeetgslab @kgrozis-arista
