### ISSUE TITLE
Remove code being printed in failure cases for pytest html reports

### ISSUE THREAD

**Issue by shachiagarwal** [aristanetworks/vane#659]
**Is your feature request related to a problem? Please describe.**
Currently failure in test prints the code of the failed functions in the pytest html reports. The users do not want this extra information. They would like to only see assertion failure.

**Describe the solution you'd like**
Only print the assertion that failed.

**Describe alternatives you've considered**
Need to investigate this in more detail to come up with the approaches to do this. One thing we need to keep in mind, that this info should get recorded in logs elsewhere too.

**Comment by kgrozis-arista** [comment]
Use this 
https://docs.pytest.org/en/7.1.x/how-to/output.html
